Design ipv6 vpc
scanlonp/aws-cdk pull request #4
Opened 2023-12-14 16:03 UTC by scanlonp

Showing this here.

2023-12-14 17:05 UTC, rix0rrr requested changes

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +          });
Can we not stick this into a method on `publicSubnet` as well?

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +export enum VpcProtocol {
Shouldn't this be `IpProtocol`, rather than `VpcProtocol` ? And the field as well?

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +   * This property is specific to dual stack VPCs.
Put in the docstring of all other relevant properties that they are explicitly for IPv4 configs only.

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +  readonly ipv6AmazonProvidedCidrBlock?: boolean;
Remove this I think?

Ultimately it will become a property more like this one:

```ts
readonly ipAddresses?: IIpAddresses;
```

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +   * @default true in Subnet.Public, false in Subnet.Private or Subnet.Isolated. Always false for dual stack VPC
Maybe phrase as "true in public subnets in IPV4_ONLY vpcs, false otherwise"

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +   * This property is specific to dual stack VPCs.
Please label all other relevant docstrings as pertaining only to IPv4.

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +      throw new Error('Do not set IPv6 properties on IPv4-only VPCs');
Error messages should be precise and actionable: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#error-messages

```ts
const ipv6OnlyProps: Array<keyof VpcProps> = ['ipv6CreateEgressOnlyInternetGateway', 'ipv6AmazonProvidedCidrBlock'];
if (this.vpcProtocol === VpcProtocol.IPV4_ONLY) {
  for (const prop of ipv6OnlyProps) {
    if (props[prop] !== undefined) {
       throw new Error(`${prop} can only be set if IPv6 is enabled. Set vpcProtocol to DUAL_STACK`');
    }
  }
}
```

or whatever

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +          });
Do we use the same internet gateway by the way?

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +          });
Why is the one `this.internetGatewayId!` and the other one `igw.ref` ?

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +    const createEigw = props.ipv6CreateEgressOnlyInternetGateway ?? true;
If the cost of the EIGW is cheap enough, I think we can do without this property.

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +      subnetIpv6Cidrs = Fn.cidr(this.ipv6Cidr, allocatedSubnets.length, (128 - 64).toString());
This feels a bit icky to me. Can't we extend `IIpAddresses.allocateSubnetsCidr` with `allocateSubnetsCidrIpv6()`, and defer the calculation to another class?

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +        // mapPublicIpOnLaunch true in Subnet.Public, false in Subnet.Private or Subnet.Isolated.
Extract all this logic out into a helper function. This is an annoying place to stick it all. 

```ts
private calculateMapPublicIpOnLaunch(config: SubnetConfig): boolean | undefined;


const subnetProps = {
  mapPublicIpOnLaunch: this.calculateMapPublicIpOnLaunch(subnetConfig),
  // ...etc...
} satisfies SubnetProps;
```

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +      if (this.vpcProtocol === VpcProtocol.IPV4_ONLY) {
Don't do a top-level if on the VPC protocol.

Do a per-property calculation that can depend on the VpcProtocol instead (if relevant).

2023-12-14 17:05 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +  private readonly vpcProtocol: VpcProtocol;
Especially if we're going to add IPV6_ONLY, I think easier to work with will be:

```ts
private readonly useIpv4: boolean;
private readonly useIpv6: boolean;
```

2023-12-21 22:05 UTC, mikewrighton commented on packages/aws-cdk-lib/aws-ec2/lib/ip-addresses.ts
> +export class amazonProvided implements IIpv6IpAddresses {
nit: `AmazonProvided`?

2023-12-23 21:27 UTC, scanlonp commented on packages/aws-cdk-lib/aws-ec2/lib/vpc.ts
> +export enum VpcProtocol {
I would say IpProtocol is redundant. I think VpcProtocol conveys what the property controls most clearly. But I am fine to change it, but personally prefer VpcProtocol.

2024-01-18 18:38 UTC, scanlonp commented
Merged into upstream here https://github.com/aws/aws-cdk/pull/28480.

2024-01-18 18:38 UTC, closed without merging